### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by pronoviol** [yafp/ttth#125]
## Expected Behavior
fine but....unhandled error

## Actual Behavior
Unhandled Error
TypeError: Error processing argument at index 0, conversion failure from CmdOrCtrl+10
    at EventEmitter.<anonymous> (/tmp/.mount_ttth-1GDHdPV/resources/app.asar/main.js:663:28)
    at WebContents.<anonymous> (/tmp/.mount_ttth-1GDHdPV/resources/electron.asar/browser/api/web-contents.js:390:13)
    at WebContents.emitter.emit (/tmp/.mount_ttth-1GDHdPV/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:56:20)

## Steps to Reproduce the Problem

  1.just open it and got this 
  1.
  1.

## Specifications

  - Version: 1.6
  - Platform:
  - Subsystem:

**Comment by pronoviol** [comment]
how to be fixed???

**Comment by yafp** [comment]
Hey pronoviol,

there is a bug in 1.6.0 where ttth tries to assign global shortcuts for each service.
This works for the first 9 services (CMD+1 up to CMD+9) but fails with number 10.

I am working on a solution - see #116 


Am i right that you have configured at least 10 services which are as well enabled?
