### ISSUE TITLE
Error opening Twitter

### ISSUE THREAD

**Issue by mauriciobc** [yafp/ttth#191]
```
TypeError: Error processing argument at index 0, conversion failure from null
    at App.setBadgeCount (electron/js2c/browser_init.js:6976:31)
    at IpcMain.<anonymous> (/opt/ttth/resources/app.asar/main.js:641:47)
    at IpcMain.emit (events.js:203:13)
    at IpcMain.EventEmitter.emit (domain.js:476:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3849:15)
    at WebContents.emit (events.js:203:13)
    at WebContents.EventEmitter.emit (domain.js:476:20)
    at WebContents.emitter.emit (/opt/ttth/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:55:20)
    at WebContents.topLevelDomainCallback (domain.js:131:23)
```

---

ttth 1.8.20200228
Electron 7.1.11
linux 5.4.0-29-generic
Locale: pt-BR

**Comment by yafp** [comment]
Hey @mauriciobc 

another user reported a similar issue -> see #182 

The temporary workaround until i was able to publish a new build is to disable the inject code for your configured twitter service.

How to: please see here: https://github.com/yafp/ttth/issues/182#issuecomment-618886946

Please let me know if this solves your issue.


Grettings

**Comment by yafp** [comment]
@mauriciobc 

did that work for you?

**Comment by mauriciobc** [comment]
I reverted to 1.8.0 and though the badge still shows NaN it does not keep throwing error messages in a loop. Will try this and get back to you soon.
