### ISSUE TITLE
Added Twitter account

### ISSUE THREAD

**Issue by skarone** [yafp/ttth#196]
```
TypeError: Error processing argument at index 0, conversion failure from null
    at App.setBadgeCount (electron/js2c/browser_init.js:6976:31)
    at IpcMain.<anonymous> (/Applications/ttth.app/Contents/Resources/app.asar/main.js:641:47)
    at IpcMain.emit (events.js:203:13)
    at IpcMain.EventEmitter.emit (domain.js:476:20)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3849:15)
    at WebContents.emit (events.js:203:13)
    at WebContents.EventEmitter.emit (domain.js:476:20)
    at WebContents.emitter.emit (/Applications/ttth.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:55:20)
    at WebContents.topLevelDomainCallback (domain.js:131:23)
```

---

ttth 1.8.20200228
Electron 7.1.11
darwin 19.6.0
Locale: en-GB

**Comment by yafp** [comment]
Hi, sorry for the late reply.
I was / am somehow busy right now.
This seems to be a duplicates bug report - please see: #191

Right now this issue is not yet fixed - but i will report back in #191 if it is done.
